---
author: "Harry Churchley"
date: "`r Sys.Date()`"
title: "Example: London Covid Deaths"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{covid-deaths}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

Install dependancies 

```{r setup}
library(trendyr)
library(dbplyr)
library(lubridate)
library(ggplot2)
library(ggrepel)
```

View data

```{r}
head(londondeathsData)
```
Run trendr on the data and save the output to a csv.

```{r}
londondeathsData_trendr <- trendr(df = londondeathsData,
              weekend_effects = FALSE,
              value.colname = "deaths",
              time.colname = "date",
              output.save = TRUE,
              output.file = "londondeathsData_trendr.csv")

head(londondeathsData_trendr)

```
Run trendr on the data and plot the results to a graph.

```{r}
londondeathsData_trendr <- trendr(df = londondeathsData,
              weekend_effects = FALSE,
              value.colname = "deaths",
              time.colname = "date",
              output.plot = TRUE)

```

Plot the data with a connected scatterplot.

```{r}
flightpath(df = londondeathsData_trendr, label_type = "ymd")
```
